export const Lore: Record<string, string> = {
  naomi: `The earliest memory Naomi has is from the Academy of Magically Gifted Children, thanks to a memory wipe spell that they cast on all new students. She spent 7 years there studying, before graduating when she turned 18. During that time, she studied solstice magic, harnessing the power of both the light and the darkness. During this time, Naomi had met Becca, though they would not come to be friends until much later.

  After the Academy, Naomi spent 6 years studying at a military school. It was there that she met both Rosalia and Melody, though only Melody would follow her after graduation. Naomi studied quite a bit of strategy here, learning leadership in both ground troop formations and space combat. Upon leaving the school, she completed her mandatory 5 years of service in a military space fleet, where she slowly climbed the ranks from trooper to officer to admiral.
  
  Naomi would then go on to her own adventures, travelling around different realms and seeing the sights. She stumbled across Becca once more, who was now wed to Rosalia. After hearing stories of their travels, Naomi decided to begin chronicling their adventures. Every few years, the three of them meet up to share tales and strengthen their bond.
  
  On one of her recent adventures, Naomi met Soup - they quickly fell in love, and wasted no time before getting married. Now, while she still goes on the occasional adventure, Naomi spends most of her time at home with her wife, with Melody taking care of things around the manor.
  
  In combat, Naomi uses her dark magic to charm and confuse her enemies, and her light magic to strengthen her allies and bolster their skills. Should she get in to a hand-to-hand encounter, Naomi prefers to use a rapier to elegantly fend off her foes. In an emergency, or should she become disarmed, she can channel a great deal of her magical engery to craft a scythe from her own blood. This takes immense focus, and should she slip up for a moment, the scythe would disintegrate and her life would end. Thankfully, she has many followers who would gladly defend her.
  
  Because she does not have much physical strength, she relies on her speed - dodging blows rather than blocking them, weakening her foes with quick, decisive strikes, and overwhelming their defences with a flurry of blows.
  
  Her powers are also directly tied to the alignment of the solar system. During a solstice, her powers are at their peak. The winter solstice heightens her dark powers, while the summer solstice heightens her light powers. Her powers wane during an equinox, but she is at her weakest during an eclipse, when her powers are completely unusable.`,
  soup: `Medusa Styggia (who goes by Soup) was the smallest of her rare breed of jellyfish and was outcast for not only her size but being known to show herself to humans when that was a very rare occasion. Outcast from the depths she wandered the seas aimlessly for years, one faithful day she came across a mermaid who had asked her why she started so far from her breeding grounds and why such a rare species was out in the open, after explaining everything the mermaid pitied her and granted her the powers of a magical girl, her tendrils and cap becoming a hat upon a human form. She used her powers for chaos to bring despair and loneliness that she had felt upon her species as well as other sea life that had mocked her, granting her the title of the one and only dark magical girl-jellyfish.`,
  melody: `Melody first met Naomi in the military school. During their time there, she succumbed to Naomi's charisma, leadership, and magical charm. Upon their graduation, Melody swore an oath to protect and serve Naomi for eternity - in exchange, Naomi granted her endless life.

  Nowadays, Melody acts as Naomi's personal assistant, helping with her day to day activities and ensuring everything goes smoothly. She also acts as a bodyguard, though it is still up for debate whether Naomi actually needs such a service.
  
  Melody has teal blue hair, which is almost always kept up in a bun. Her left eye is green, while her right eye is teal. She often wears teal lipstick and eye shadow, and is most frequently seen in a neutral grey suit.
  
  When protecting her mistress Naomi, Melody typically reaches for throwing knives or a dagger. She prefers a stealthy approach, avoiding direct hand-to-hand combat. But should such a situation become necessary, Melody is also quite deft with a rapier.`,
  becca: `Becca is a young female wizard fuelled primarily by the pursuit of knowledge. She travels the multiverse, always searching for new things to learn. Known for being friendly to those she meets, Becca keeps them at a distance, with Rosalia being her only close, trusted companion. While she has been seen traveling with others, it's only when the situation calls for it. Her true age is unknown, even to herself, but her physical age remains 21.

  An orphan who grew up on the streets of a small village, Becca had to struggle to survive day to day. Due to her challenging past, she finds it difficult to form deep emotional bonds with others, as trust is hard to come by. At the age of 8, she was caught by the town guard attempting to steal a rare gem. In the resulting altercation, she unintentionally called lightning down on a guardsman, catching the attention of the nearest Academy. Subsequently, she was sent there for magical training, spending 10 years studying and strengthening her control over lightning. During her time in the Academy, she explored necromancy, but her professors prohibited further exploration in that field. Bitter and frustrated about the imposed restrictions, she bid farewell to the Academy when she discovered the methods for interplanar travel, continuing her studies independently.
  
  Becca has soft white hair kept in pigtails, deep purple eyes, and pale skin. Despite not needing them, she wears glasses and is always seen in purple clothing, usually a dress but sometimes other outfits. Her outfits are cute and elegant, drawing attention when she dresses up. When not traveling, she opts for more comfortable clothing. Purple lipstick, eye shadow, and painted fingernails complete her distinct look. Her expressions often range from a neutral gaze to a focused one as she constantly observes her surroundings.
  
  As a fulgramancer and necromancer, Becca specializes in lightning and death magic, bringing destruction to her foes from a distance. She prefers to avoid close combat, employing stealth as needed to remain unseen by her targets. Her magical prowess grants her near-immortality; she can't be killed, and when faced with a fatal blow, she retreats to a private plane of existence to absorb magical energies and recover strength. Becca sometimes uses a wand or staff to channel her magical energies but is just as capable when completely unarmed.
  
  Falling under the Chaotic Neutral alignment, Becca doesn't go out of her way to help others but also avoids unnecessarily inflicting harm. Theft and murder are not her methods, but she will do whatever is necessary to fulfill a job contract or request. Once a contract is established with a promised payment, she considers it binding, showing fierce loyalty to her clients. This loyalty has earned her a strong reputation as reliable, leading to frequent requests for her services. Despite this, she often turns down requests that would divert her from her quest for learning.`,
  rosalia: `Rosalia is a young female paladin motivated by a primary desire to protect and assist others, particularly those who are weak or unfortunate. She travels across various lands, aiming to bring positivity to people's lives. Many consider her very friendly, but her trusting nature occasionally leads to trouble. Thanks to the blessing of the goddess, she stopped aging at 25.

  Growing up in a small town with loving parents and close friends, Rosalia faced tragedy at the age of 12 when her village was raided by local bandits. Many close to her, including her parents, did not survive. This event spurred her commitment to protecting others, leading her to enlist in the royal guard at the local lord's palace after three years of training. During her first mission to investigate a bandit attack, she discovered a temple where she connected with the Goddess, receiving her holy power.
  
  Rosalia has long black hair, dark green eyes, and pale skin. She always wears white, opting for a robe during adventures and a dress for more formal events. Choosing not to wear makeup, she prefers to spend her time helping others rather than focusing on her appearance. Additionally, she never wears shoes, finding that it allows her to move much quicker.
  
  As a paladin, Rosalia possesses holy abilities that enable her to heal the wounded, turn away those of evil heart, and even bring someone back from the brink of death on rare occasions. Her chosen weapon is the greatsword, allowing her to strike fiercely and true, smiting evil at its root. Confident in the protection of the Goddess, she forgoes armor for increased agility.
  
  Considered Lawful Good and a champion of justice, Rosalia's primary goal is to help others without participating in evil acts. Murder, thievery, and other harmful deeds are unacceptable to her. Discovering attempts to deceive her into committing such wrongdoings result in fierce retribution. However, as long as a request aligns with her values, she does everything in her power to assist. Rosalia often refuses payment, only accepting enough to cover her basic needs when required.`,
};
